#!/usr/bin/env php
<?php

require_once __DIR__ . '/Facebook/autoload.php';

if (file_exists(__DIR__ . '/config.php')) { include __DIR__ . '/config.php'; } else { die('Could not load config'.PHP_EOL); }

if (file_exists(__DIR__ . '/album.php'))  { include __DIR__ . '/album.php'; }
if (file_exists(__DIR__ . '/auth.php'))   { include __DIR__ . '/auth.php'; }
if (file_exists(__DIR__ . '/base.php'))   { include __DIR__ . '/base.php'; }
if (file_exists(__DIR__ . '/file.php'))   { include __DIR__ . '/file.php'; }

# Token to access FB
$config['accessToken'] = ''; $config['pageToken'] = '';
if (file_exists(__DIR__ . '/token.php')) { include __DIR__ . '/token.php'; }
if ($config['accessToken'] == '') { getAccessToken(); }
if ($config['pageToken'] == '')   { getPageToken(); }

// Listing photo folder ready to upload
$f = scandir($config['cloudPath']);
// Cleaning array
$content = array();
foreach($f as $index=>$folder) {
  if (!preg_match('/^([0-9]{8}) ([0-9]+) /',$folder)) { unset($f[$index]); }
}

$resp = TRUE;
while ($resp) {
  echo "Listing current Shoots directories :".PHP_EOL;
  foreach($f as $index=>$folder) {
    preg_match('/^([0-9]{8}) ([0-9]+) (.+$)/',$folder,$match);
    echo "  [".$index."] => ".$match[1]." ".$match[3].PHP_EOL;
  }
  echo "Which folder do you want to upload ?".PHP_EOL;
  $h = fopen("php://stdin","r");
  $reply = fgets($h);
  if (!preg_match('/^[0-9]+$/',$reply)) { echo "Please enter the ID of the folder.".PHP_EOL; continue; }
  if (!isset($f[(int) $reply])) { echo "Please enter an existing ID.".PHP_EOL; continue; }
  preg_match('/^([0-9]{8}) ([0-9]+) (.+$)/',$f[(int) $reply],$m);
  if (!checkAlbumID($m[2])) { echo "This album doesn't exist on facebook or refuse new uploads.".PHP_EOL; continue; }
  $resp = FALSE;
  $choice = $f[(int) $reply];
}
preg_match('/^([0-9]{8}) ([0-9]+) (.+$)/',$choice,$m);
$choices['date'] = $m[1];
$choices['albumID'] = $m[2];
$choices['name'] = $m[3];
echo "Selected folder is : ".$choices['date']." ".$choices['albumID']." ".$choices['name'].PHP_EOL;

// Check which photographers are in folders
$pgrapher = scandirStrict($config['cloudPath']."/".$choice);

// Validation of upload
$error = TRUE;
$turn = 1;
$sleeptime = 12;
while ($error) {
  $error = FALSE;
  echo "Begin turn $turn".PHP_EOL;
  // Get list of photos in album
  $photolist = getPhotoList($choices['albumID']);
  foreach($pgrapher as $p) {
    $dir = scandirStrict($config['cloudPath']."/".$choice."/".$p);
    foreach($dir as $photo) {
      preg_match('/[_-]([0-9]+)\./',$photo,$m);
      $caption = strtoupper(substr($p,0,1)).$m[1].")";
      $check = FALSE;
      foreach($photolist as $ULphoto) {
        if ($caption == $ULphoto['name']) { $check = TRUE; break; }
      }
      if ($check == FALSE) {
        if ($turn > 1) { echo "/!\ WARNING /!\ Photo $caption is not uploaded !!!".PHP_EOL; }
        $photouri = preg_replace('/ /','%20',"https://".$config['cloudUri']."/".$choice."/".$p."/".$photo);
        echo " => Uploading ".$photo." with caption \"".$caption."\" via uri ".$photouri.PHP_EOL;
        uploadPhotoToAlbum($choices['albumID'], $photouri, $caption);
        sleep(2);
        $error = TRUE;
      } else {
        if ($turn == 1) { continue; }
        // TODO move files to published photos folder
        moveFileToPublished($config['cloudPath']."/".$choice."/".$p."/".$photo, $config['cloudPathPublished']."/".$choice."/".$p."/".$photo);
      }
    }
  }

  echo "Waiting $sleeptime seconds for not overloading API".PHP_EOL;
  sleep($sleeptime);
  if ($turn == 1) { $error = TRUE; }
  $turn++;
  $sleeptime = $sleeptime * 5;
}

exit();

