#!/usr/bin/env php
<?php

require_once __DIR__ . '/Facebook/autoload.php';

if (file_exists(__DIR__ . '/config.php')) { include __DIR__ . '/config.php'; } else { die('Could not load config'.PHP_EOL); }

if (file_exists(__DIR__ . '/album.php'))  { include __DIR__ . '/album.php'; }
if (file_exists(__DIR__ . '/auth.php'))   { include __DIR__ . '/auth.php'; }
if (file_exists(__DIR__ . '/base.php'))   { include __DIR__ . '/base.php'; }

# Token to access FB
$config['accessToken'] = ''; $config['pageToken'] = '';
if (file_exists(__DIR__ . '/token.php')) { include __DIR__ . '/token.php'; }
if ($config['accessToken'] == '') { getAccessToken(); }
if ($config['pageToken'] == '')   { getPageToken(); }

// Listing photo folder ready to upload
$f = scandir($config['cloudpath']);
// Cleaning array
$content = array();
foreach($f as $index=>$folder) {
  if (!preg_match('/^([0-9]{8}) ([0-9]+) /',$folder)) { unset($f[$index]); }
}
// Parsing array
#foreach($f as $index=>$folder) {
#  preg_match('/^([0-9]{8}) ([0-9]+) /',$folder,$match);
#  $content[$match[2]] = $folder;
#}

$resp = TRUE;
while ($resp) {
  echo "Listing current Shoots directories :".PHP_EOL;
  foreach($f as $index=>$folder) {
    preg_match('/^([0-9]{8}) ([0-9]+) (.+$)/',$folder,$match);
    echo "  [".$index."] => ".$match[1]." ".$match[3].PHP_EOL;
  }
  echo "Which folder do you want to upload ?".PHP_EOL;
  $h = fopen("php://stdin","r");
  $reply = fgets($h);
  if (!preg_match('/^[0-9]+$/',$reply)) { echo "Please enter the ID of the folder.".PHP_EOL; continue; }
  if (!isset($f[(int) $reply])) { echo "Please enter an existing ID.".PHP_EOL; continue; }
  preg_match('/^([0-9]{8}) ([0-9]+) (.+$)/',$f[(int) $reply],$m);
  if (!checkAlbumID($m[2])) { echo "This album doesn't exist on facebook or refuse new uploads.".PHP_EOL; continue; }
  $resp = FALSE;
  $choice = $f[(int) $reply];
}
preg_match('/^([0-9]{8}) ([0-9]+) (.+$)/',$choice,$m);
$choices['date'] = $m[1];
$choices['albumID'] = $m[2];
$choices['name'] = $m[3];
echo "Selected folder is : ".$choices['date']." ".$choices['albumID']." ".$choices['name'].PHP_EOL;

// Check which photographers are in folders
$pgrapher = scandirStrict($config['cloudpath']."/".$choice);

// List all images
foreach($pgrapher as $p) {
  $dir = scandirStrict($config['cloudpath']."/".$choice."/".$p);
  foreach($dir as $photo) {
    preg_match('/[_-]([0-9]+)\./',$photo,$m);
    $caption = strtoupper(substr($p,0,1)).$m[1];
    $photouri = preg_replace('/ /','%20',"https://".$config['clouduri']."/".$choice."/".$p."/".$photo);
    echo " => Uploading ".$photo." with caption \"".$caption."\" via uri ".$photouri.PHP_EOL;
    uploadPhotoToAlbum($choices['albumID'], $photouri, $caption);
  }
}

exit();

